version: '3'

services:
  repos_api:
    build:
      context: apps/repos-api
    ports:
      - '3000:3000'
    env_file:
      - apps/repos-api/.env
    depends_on:
      - redis
    environment:
      REDIS_URL: redis://redis:6379
  users_api:
    build:
      context: apps/users-api
    ports:
      - '4000:4000'
    env_file:
      - apps/users-api/.env
    depends_on:
      - mongodb
    environment:
      MONGO_URI: mongodb://mongodb:27017/users-data

  redis:
    image: redis:latest
    ports:
      - '6379:6379'

  mongodb:
    image: mongo:latest
    ports:
      - '27017:27017'
